import type { Metadata } from "next";
import "./styles/globals.css";
import StoreProvider from "./providers/StoreProvider";
import {
  basier,
  inter,
  junicode,
  roboto,
  switzer,
} from "@/shared/assets/fonts/fonts";
import { Header } from "@/widgets/Header/ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${switzer.variable} ${basier.variable} ${junicode.variable} ${roboto.variable} ${inter.variable} antialiased`}
      >
        <StoreProvider>
          <div className="main-container">
            <Header />
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
